"""initial migration

Revision ID: 5e96c3b8d67d
Revises: c8eb0e1cc4fc
Create Date: 2016-10-02 10:56:16.350165

"""

# revision identifiers, used by Alembic.
revision = '5e96c3b8d67d'
down_revision = 'c8eb0e1cc4fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('http_api',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodepool_policy',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=True),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('scaleup_adjust', sa.Integer(), nullable=True),
    sa.Column('scaleup_cooldown', sa.Integer(), nullable=True),
    sa.Column('scaleup_period', sa.Integer(), nullable=True),
    sa.Column('scaleup_evaluation_periods', sa.Integer(), nullable=True),
    sa.Column('scalueup_threshold', sa.Integer(), nullable=True),
    sa.Column('scaledown_adjust', sa.Integer(), nullable=True),
    sa.Column('scaledown_cooldown', sa.Integer(), nullable=True),
    sa.Column('scaledown_period', sa.Integer(), nullable=True),
    sa.Column('scaledown_evaluation_periods', sa.Integer(), nullable=True),
    sa.Column('scaledown_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('http_api_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_header',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('http_api_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_error_message',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('response_statuscode_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_statuscode',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status_code', sa.String(length=3), nullable=True),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('container')
    op.drop_table('gateway')
    op.drop_table('policy')
    op.add_column(u'function', sa.Column('desc', sa.Text(), nullable=True))
    op.add_column(u'nodepool', sa.Column('function_id', sa.String(length=36), nullable=True))
    op.add_column(u'nodepool', sa.Column('nodepool_policy_id', sa.String(length=36), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'nodepool', 'nodepool_policy_id')
    op.drop_column(u'nodepool', 'function_id')
    op.drop_column(u'function', 'desc')
    op.create_table('policy',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_vm_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('vm_count_per_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('gateway',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stack_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('ports', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('container',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('project_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stack_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nodepool_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('memory', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('response_statuscode')
    op.drop_table('response_error_message')
    op.drop_table('response')
    op.drop_table('request_header')
    op.drop_table('request')
    op.drop_table('nodepool_policy')
    op.drop_table('http_api')
    op.drop_table('endpoint')
    ### end Alembic commands ###
