"""Update NodePool

Revision ID: 88c36cb5f12c
Revises: 8a3fda962ef5
Create Date: 2016-10-02 23:46:17.718546

"""

# revision identifiers, used by Alembic.
revision = '88c36cb5f12c'
down_revision = '8a3fda962ef5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'status_reason')
    op.add_column('nodepool', sa.Column('status_reason', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodepool', 'status_reason')
    op.add_column('function', sa.Column('status_reason', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
