"""Update NodePool and NodePoolPolicy

Revision ID: 8a3fda962ef5
Revises: b8388d720161
Create Date: 2016-10-02 23:44:00.460823

"""

# revision identifiers, used by Alembic.
revision = '8a3fda962ef5'
down_revision = 'b8388d720161'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
