"""Add a name column on NodePoolPolicy

Revision ID: a4d56bb32148
Revises: 5e96c3b8d67d
Create Date: 2016-10-02 11:04:43.471850

"""

# revision identifiers, used by Alembic.
revision = 'a4d56bb32148'
down_revision = '5e96c3b8d67d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodepool_policy', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodepool_policy', 'name')
    ### end Alembic commands ###
