"""Fix the typo

Revision ID: b8388d720161
Revises: a4d56bb32148
Create Date: 2016-10-02 11:35:25.028066

"""

# revision identifiers, used by Alembic.
revision = 'b8388d720161'
down_revision = 'a4d56bb32148'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodepool_policy', sa.Column('scaleup_threshold', sa.Integer(), nullable=True))
    op.drop_column('nodepool_policy', 'scalueup_threshold')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodepool_policy', sa.Column('scalueup_threshold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('nodepool_policy', 'scaleup_threshold')
    ### end Alembic commands ###
