"""Update Tables

Revision ID: f37ffbefe5de
Revises: 88c36cb5f12c
Create Date: 2016-11-10 19:21:57.830233

"""

# revision identifiers, used by Alembic.
revision = 'f37ffbefe5de'
down_revision = '88c36cb5f12c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('endpoint', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('function', sa.Column('endpoint_id', sa.String(length=36), nullable=True))
    op.add_column('function', sa.Column('nodepool_id', sa.String(length=36), nullable=True))
    op.drop_column('function', 'trustee_password')
    op.drop_column('function', 'trustee_user_id')
    op.drop_column('function', 'trustee_username')
    op.drop_column('function', 'trust_id')
    op.add_column('nodepool_policy', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('nodepool_policy', sa.Column('user_id', sa.String(length=36), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodepool_policy', 'user_id')
    op.drop_column('nodepool_policy', 'project_id')
    op.add_column('function', sa.Column('trust_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('function', sa.Column('trustee_username', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('function', sa.Column('trustee_user_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('function', sa.Column('trustee_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('function', 'nodepool_id')
    op.drop_column('function', 'endpoint_id')
    op.drop_column('endpoint', 'user_id')
    op.drop_column('endpoint', 'project_id')
    ### end Alembic commands ###
